import { Loan, Transaction } from './types';

export const INITIAL_LOANS: Loan[] = [
  {
    id: 'loan-1',
    businessName: 'Greenwood Artisanal Bakery',
    category: 'Food & Beverage',
    description: 'Artisanal sourdough bakery expansion and specialty brick oven installation.',
    requestedAmount: 18000,
    fundedAmount: 18000,
    termMonths: 12,
    interestRate: 0.20,
    status: 'REPAYING',
    createdAt: '2026-05-10',
    borrowerEmail: 'owner@greenwoodbakery.com',
    lenderId: 'projectile.afk@gmail.com',
    paymentsMade: 5,
    totalPaid: 9000, // 5 payments of 1800 (calculated as: 18000 * 1.2 / 12 = 1800 per month)
  },
  {
    id: 'loan-2',
    businessName: 'Apex Precision Machining',
    category: 'Manufacturing',
    description: 'High-precision manufacturing machinery upgrades and professional toolsets.',
    requestedAmount: 45000,
    fundedAmount: 45000,
    termMonths: 18,
    interestRate: 0.20,
    status: 'REPAYING',
    createdAt: '2026-04-15',
    borrowerEmail: 'procurement@apexprecision.com',
    lenderId: 'projectile.afk@gmail.com',
    paymentsMade: 4,
    totalPaid: 12000, // 4 payments of 3000 (calculated as: 45000 * 1.2 / 18 = 3000 per month)
  },
  {
    id: 'loan-3',
    businessName: 'Solstice Solar Installers',
    category: 'Personal & Emergency',
    description: 'Urgent solar panel cell replacement parts and booster inverter components.',
    requestedAmount: 1000,
    fundedAmount: 1000,
    termMonths: 6,
    interestRate: 0.20,
    status: 'REPAYING',
    createdAt: '2026-07-18',
    borrowerEmail: 'ops@solsticesolar.co',
    lenderId: 'projectile.afk@gmail.com',
    paymentsMade: 1,
    totalPaid: 200, // 1 payment of 200 (calculated as: 1000 * 1.2 / 6 = 200 per month)
  },
  {
    id: 'loan-4',
    businessName: 'Lakeside Pediatrics Care',
    category: 'Healthcare',
    description: 'Pediatric health clinic medical device purchase and sterile equipment financing.',
    requestedAmount: 65000,
    fundedAmount: 0,
    termMonths: 24,
    interestRate: 0.20,
    status: 'MARKETPLACE',
    createdAt: '2026-07-20',
    borrowerEmail: 'dr.thompson@lakesidepediatrics.org',
    lenderId: null,
    paymentsMade: 0,
    totalPaid: 0,
  },
  {
    id: 'loan-5',
    businessName: 'ByteFlow Software Solutions',
    category: 'Technology',
    description: 'Server infrastructure setup and local high-performance hardware leasing.',
    requestedAmount: 25000,
    fundedAmount: 0,
    termMonths: 12,
    interestRate: 0.20,
    status: 'MARKETPLACE',
    createdAt: '2026-07-20',
    borrowerEmail: 'founders@byteflow.ai',
    lenderId: null,
    paymentsMade: 0,
    totalPaid: 0,
  },
  {
    id: 'loan-6',
    businessName: 'SwiftRoute Logistics',
    category: 'Logistics & Transport',
    description: 'Logistics shipping fleet support and domestic travel relocation logistics.',
    requestedAmount: 15000,
    fundedAmount: 15000,
    termMonths: 6,
    interestRate: 0.20,
    status: 'PAID',
    createdAt: '2026-01-10',
    borrowerEmail: 'fleet@swiftroute.net',
    lenderId: 'projectile.afk@gmail.com',
    paymentsMade: 6,
    totalPaid: 18000, // 6 payments of 3000 (calculated as: 15000 * 1.2 / 6 = 3000 per month)
  }
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    loanId: 'loan-1',
    loanName: 'Greenwood Artisanal Bakery',
    type: 'FUNDING',
    amount: 18000,
    timestamp: '2026-05-10T09:30:00Z',
    sender: 'projectile.afk@gmail.com',
    receiver: 'owner@greenwoodbakery.com',
  },
  {
    id: 'tx-2',
    loanId: 'loan-2',
    loanName: 'Apex Precision Machining',
    type: 'FUNDING',
    amount: 45000,
    timestamp: '2026-04-15T14:15:00Z',
    sender: 'projectile.afk@gmail.com',
    receiver: 'procurement@apexprecision.com',
  },
  {
    id: 'tx-3',
    loanId: 'loan-3',
    loanName: 'Solstice Solar Installers',
    type: 'FUNDING',
    amount: 1000,
    timestamp: '2026-07-18T11:00:00Z',
    sender: 'projectile.afk@gmail.com',
    receiver: 'ops@solsticesolar.co',
  },
  {
    id: 'tx-4',
    loanId: 'loan-1',
    loanName: 'Greenwood Artisanal Bakery',
    type: 'REPAYMENT',
    amount: 9000,
    timestamp: '2026-07-10T18:00:00Z',
    sender: 'owner@greenwoodbakery.com',
    receiver: 'projectile.afk@gmail.com',
  },
  {
    id: 'tx-5',
    loanId: 'loan-2',
    loanName: 'Apex Precision Machining',
    type: 'REPAYMENT',
    amount: 12000,
    timestamp: '2026-07-15T18:00:00Z',
    sender: 'procurement@apexprecision.com',
    receiver: 'projectile.afk@gmail.com',
  },
  {
    id: 'tx-6',
    loanId: 'loan-3',
    loanName: 'Solstice Solar Installers',
    type: 'REPAYMENT',
    amount: 200,
    timestamp: '2026-07-19T18:00:00Z',
    sender: 'ops@solsticesolar.co',
    receiver: 'projectile.afk@gmail.com',
  },
  {
    id: 'tx-7',
    loanId: 'loan-6',
    loanName: 'SwiftRoute Logistics',
    type: 'FUNDING',
    amount: 15000,
    timestamp: '2026-01-10T10:00:00Z',
    sender: 'projectile.afk@gmail.com',
    receiver: 'fleet@swiftroute.net',
  },
  {
    id: 'tx-8',
    loanId: 'loan-6',
    loanName: 'SwiftRoute Logistics',
    type: 'REPAYMENT',
    amount: 18000,
    timestamp: '2026-07-10T10:00:00Z',
    sender: 'fleet@swiftroute.net',
    receiver: 'projectile.afk@gmail.com',
  }
];
